export enum ApiRoutesEnum {
  REGISTER_DEVICE = '/user/register-device',
  SIGNIN = '/auth/app/signin',
  PROFILE = '/user/profile',
  REDEEM_TOKEN = '/user/redeem-token',
  ADDRESS = '/address',
  PROFESSIONS = '/professions',
  COMPLETE_PROFILE = '/user/complete-account',
  FORGOT_PASSWORD = '/auth/recovery-account',
  FORGOT_PASSWORD_RESET = '/auth/reset-password',
  UPDATE_ACCOUNT = '/user/update-account',
  CHECK_IN = '/checkin/app',
  SECONDARY_EMAIL = '/user/secondary-email',
  OPTIN_GET = '/user/campaign/search',
  OPTIN_POST = '/user/campaign/accept',
  CONSENT_OPTIONS = '/auth/consent-options',
  SIGNUP = '/auth/app/signup',
  SIGNUP_VERIFY = '/auth/activate-account',
  ACCOUNT_OPTIONS = '/auth/recovery-account-options',
  RESEND_CODE = '/auth/app/resend-activate-account-email',
  EVENTS = '/events',
  STORES = '/stores',
  CREATE_SESSION = '/auth/create-session',
  NOTIFICATIONS = '/user/notifications',
  UPDATE_NOTIFICATION_PREFERENCES = '/user/notifications/preferences',
}
export enum AuthStatusEnum {
  MUST_VALIDATE = 'must_validate',
  SUCCESS = 'success',
}
export enum RoutesEnum {
  FACE_ID = '/face-id',
  FACE_ID_CONFIG = '/face-id/config',
  FACE_ID_MODAL = 'faceid-modal',
  TWO_FACTOR = '/twofactor',
  HOME = '/home',
  LOGIN = '/login',
  ALLOW_FACE_ID = '/allow-face-id',
  NOT_ALLOW_FACE_ID = '/not-allow-face-id',
  PROFILE = '/profile',
  PROFILE_ACCOUNT = '/profile/account',
  INTRO = '/Intro',
  SIGNUP_MODAL = 'signup-modal',
  CHECK_IN = '/home/check-in',
  ADDRESS_FORM = '/profile/form/address',
  BUSINESS_FORM = '/profile/form/business',
  LAST_PROFILE_FORM = '/profile/form/last',
  FORGOT_PASSWORD = '/forgot-password',
  FORGOT_PASSWORD_FORM = '/forgot-password/form',
  FORGOT_PASSWORD_SUCCESS = '/forgot-password/success',
  FORGOT_PASSWORD_STRATEGY = '/forgot-password/strategy',
  FORGOT_PASSWORD_VERIFICATION_CODE = '/forgot-password/verification-code',
  SIGNUP = '/signup',
  CPF_FORM = '/signup/cpf',
  SIGNUP_PASSWORD = '/signup/password',
  SIGNUP_TERMS = '/signup/terms',
  SIGNUP_VERIFY = '/signup/verify',
  SIGNUP_SUCCESS = '/signup/success',
  CHECK_IN_MODAL = 'checkIn/modal',
  CHECK_IN_SUCCESS = 'checkIn/success',
  CHECK_IN_CONFIRM = '/checkinConfirm',
  CONSENT_OPTIONS = '/consent-options',
  MEMBER_GET_MEMBER = '/signup/member-get-member',
  EXTRATO = '/home/extrato',
}
export enum SecureStoreEnum {
  API_TOKEN = 'API_TOKEN',
}
export enum StorageEnum {
  ALLOWED_FACE_ID = 'NOT_ALLOW_FACE_ID',
  EXPIRES_IN = 'EXPIRES_IN',
  API_TOKEN = 'API_TOKEN',
  X_SESSION_TOKEN = 'x-session-token',
  SENSEDIA_EXPIRATION_TIME = 'expirationTimeToken',
  LATEST_RUNTIME_VERSION = 'LATEST_RUNTIME_VERSION',
  LATEST_UPDATES = 'LATEST_UPDATES',
  ACCEPTED_NOTIFICATIONS = 'ACCEPTED_NOTIFICATIONS',
}

export enum EXPO_PUSH_PERMISSION {
  GRANTED = 'granted',
  DENIED = 'denied',
  UNDETERMINED = 'undetermined',
}
